### ISSUE TITLE
Enable/Disable running tests (Nice to have)

### ISSUE THREAD

**Issue by francoiscabrol** [mad-eye/meteor-mocha-web#101]
Hi,
It could be nice to have the possibility to enable/disable the tests through the Meteor.settings (see http://docs.meteor.com/#/full/meteor_settings)

If you think it is a good idea, I could even implement it!

**Comment by rissem** [comment]
@francoiscabrol I realize I'm super late on this one, but I do think it's a good idea, and I'm definitely open to a pull request.

**Comment by semikolon** [comment]
Definitely want this as well.

**Comment by smeijer** [comment]
I would like to suggest to share the `VELOCITY=0` environment variable for this purpose.

also see: https://github.com/meteor-velocity/velocity/issues/270

**Comment by rissem** [comment]
`VELOCITY=0` stops tests from running now.
