### ISSUE TITLE
Crushing on Meteor 1.0.2.1 Error: spawn ENOENT

### ISSUE THREAD

**Issue by bobiblazeski** [mad-eye/meteor-mocha-web#121]
I've tested both in my project and created new application, the results are as below:

W20150111-14:33:44.461(1)? (STDERR) events.js:72
W20150111-14:33:44.462(1)? (STDERR)         throw er; // Unhandled 'error' event
W20150111-14:33:44.462(1)? (STDERR)               ^
W20150111-14:33:44.463(1)? (STDERR) Error: spawn ENOENT
W20150111-14:33:44.463(1)? (STDERR)     at errnoException (child_process.js:1001:11)
W20150111-14:33:44.463(1)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:792:34)

meteor list                  
autopublish      1.0.2  Publish the entire database to all clients
insecure         1.0.2  Allow all database writes by default
meteor-platform  1.2.1  Include a standard set of Meteor packages in your app
mike:mocha       0.5.1  Run mocha tests in the browser
velocity:core    0.4.5  Velocity, a Meteor specific test-runner

The code is brand new application created with meteor create app

**Comment by taji** [comment]
Same problem here. 

Clean install of meteor 1.0.3.1

meteor list
accounts-password  1.0.6  Password support for accounts
insecure           1.0.2  Allow all database writes by default
iron:router        0.9.4* Routing specifically designed for Meteor
less               1.0.12  The dynamic stylesheet language
meteor-platform    1.2.1  Include a standard set of Meteor packages in your app
mike:mocha         0.5.1  Run mocha tests in the browser

Running on Lubuntu 14.10.

**Comment by funkybunky** [comment]
I just ran into the same issue. added it to sample todos app. running on Ubuntu 14.04

**Comment by bobiblazeski** [comment]
I'm also using Ubuntu 14.04

**Comment by taji** [comment]
I fixed this.  Sorry, away from my notes but google "ENOENT nvm".   I ended up fixing it by installing nvm (node version manager), then running "nvm install stable", "nvm use stable"  and then running meteor. This ensures that you are running the latest stable version of node with meteor.

**Comment by bobiblazeski** [comment]
@taji  nvm works for me, thanks
