### ISSUE TITLE
Update velocity:node-soft-mirror

### ISSUE THREAD

**Issue by pcorey** [mad-eye/meteor-mocha-web#125]
This package is using velocity:node-soft-mirror 0.2.4. https://github.com/mad-eye/meteor-mocha-web/blob/master/package.js#L24

This version of node-soft-mirror spawns an instance of node on the path, instead of using Meteor's node instance. This can be pretty annoying if the system's node version is below Meteor's required version (v0.10.33).

velocity:node-soft-mirror 0.2.7 made a change to spawn Meteor's node instead. https://github.com/meteor-velocity/node-soft-mirror/blob/v0.2.7/nodeMirrorServer.js#L64 We should upgrade to at least this version.

Thanks!

**Comment by stubailo** [comment]
+1 - I don't want to have to manage node versions manually on my system

**Comment by stubailo** [comment]
@mad-eye I think this is a serious issue for new users.

1. You install meteor
2. You get velocity
3. You install the package that is the first one on the velocity home page, `mike:mocha`
4. You see the error: `[velocity-mirror] Meteor requires Node v0.10.33 or later.`
4. You assume velocity doesn't work and uninstall it forever

Can we please get this fixed as soon as possible? @rdickert this is the issue I was talking about

**Comment by pcorey** [comment]
Thanks guys!

**Comment by rissem** [comment]
Running into some issues publishing at the moment..might be an hour or two before this is live.

**Comment by rissem** [comment]
Released :-)
