### ISSUE TITLE
Where are stubs?

### ISSUE THREAD

**Issue by zda** [mad-eye/meteor-mocha-web#128]
Sinon.js isn't used, and I'm not sure how I would stub something like `Meteor.user()` in Mocha. As in, prevent the original from being called and specify the return value of the stub.

**Comment by marekrogala** [comment]
:+1:

**Comment by rissem** [comment]
I'd suggest using [meteor-sinon](https://github.com/practicalmeteor/meteor-sinon) by @practicalmeteor

I don't think it makes sense to bring this into the mocha package if possible.
