### ISSUE TITLE
Using Typescript

### ISSUE THREAD

**Issue by ameent** [mad-eye/meteor-mocha-web#131]
Hello there,

In the readme you mention that you are free to use any language you want, but in practice I can't get this to work. If you add any .ts files under tests/mocha/server (or client), the files are not recognized.

As far as I can tell, a package is dynamically generated that adds a dependency on files under tests/mocha which is then run in the mirror. The package definition includes a dependency on coffeescript, but does not take dependency on anything else (in this case, typescript).

Whatever component generates that file should take a look at the existing projects and add dependencies on all build packages.

Thanks!
-Ameen

**Comment by ameent** [comment]
Could https://github.com/mad-eye/meteor-mocha-web/blob/master/server.js#L9 be the culprit?

**Comment by rissem** [comment]
It certainly could. I'll try and fix/test that soon. Or if you want to take a stab at it, I'm definitely open to pull requests.

**Comment by ameent** [comment]
https://github.com/mad-eye/meteor-mocha-web/pull/133

**Comment by rissem** [comment]
Merged your pull request. Thanks!
