### ISSUE TITLE
Mirror fails to run

### ISSUE THREAD

**Issue by rdickert** [mad-eye/meteor-mocha-web#132]
After installing node-soft-mirror to solve #125, my testing is still broken. Any ideas on how to proceed? This was on a freshly created app.

➜  testvelo  VELOCITY_DEBUG_MIRROR=1 DEBUG=1 MOCHA_WEB_DEBUG=1 VELOCITY_DEBUG=1 meteor
[[[[[ ~/code/tmp/testvelo ]]]]]

=> Started proxy.
=> Started MongoDB.
I20150219-11:58:34.620(-8)? ** You've set up some data subscriptions with Meteor.publish(), but
I20150219-11:58:34.621(-8)? ** you still have autopublish turned on. Because autopublish is still
I20150219-11:58:34.621(-8)? ** on, your Meteor.publish() calls won't have much effect. All data
I20150219-11:58:34.621(-8)? ** will still be sent to all clients.
I20150219-11:58:34.622(-8)? **
I20150219-11:58:34.622(-8)? ** Turn off autopublish by removing the autopublish package:
I20150219-11:58:34.622(-8)? **
I20150219-11:58:34.622(-8)? **   $ meteor remove autopublish
I20150219-11:58:34.622(-8)? **
I20150219-11:58:34.622(-8)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20150219-11:58:34.622(-8)? ** for each collection that you want clients to see.
I20150219-11:58:34.622(-8)?
I20150219-11:58:34.622(-8)? [velocity] adding velocity core
I20150219-11:58:34.623(-8)? [velocity] Not adding mirror-registrar because NODE_ENV is development and IS_MIRROR is false
I20150219-11:58:34.701(-8)? [node-soft-mirror] adding server code
I20150219-11:58:34.702(-8)? [velocity] Velocity not started. Queueing func
I20150219-11:58:34.702(-8)? [velocity] Server startup
I20150219-11:58:34.702(-8)? [velocity] app dir /Users/robertdickert/code/tmp/testvelo
I20150219-11:58:34.702(-8)? [velocity] config = {
I20150219-11:58:34.702(-8)?   "mocha": {
I20150219-11:58:34.702(-8)?     "regex": "mocha/.+\\.(js|coffee|litcoffee|coffee\\.md)$",
I20150219-11:58:34.702(-8)?     "name": "mocha",
I20150219-11:58:34.702(-8)?     "_regexp": {}
I20150219-11:58:34.702(-8)?   }
I20150219-11:58:34.703(-8)? }
I20150219-11:58:34.703(-8)? [velocity] resetting the world
I20150219-11:58:34.703(-8)? [velocity] frameworks with disable auto reset: []
I20150219-11:58:34.703(-8)? [velocity-node-mirror] Server restarted.
I20150219-11:58:34.703(-8)? [velocity-node-mirror] Aggressively restarting all mirrors
I20150219-11:58:34.703(-8)? [node-soft-mirror]: LongRunningChildProcess.constructor(taskName=mocha)
I20150219-11:58:34.703(-8)? [node-soft-mirror]: LongRunningChildProcess.readPid()
I20150219-11:58:34.703(-8)? [node-soft-mirror]: LongRunningChildProcess.readPid returns 1204
I20150219-11:58:34.703(-8)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20150219-11:58:34.703(-8)? [node-soft-mirror] Mirror for framework mocha is not running
I20150219-11:58:34.703(-8)? [node-soft-mirror] Aggressively reload client
=> Started your app.

=> App running at: http://localhost:3000/
I20150219-11:58:34.742(-8)? [velocity] Target framework for tests/mocha/client/sampleClientTest.js is mocha
I20150219-11:58:34.744(-8)? [velocity] Target framework for tests/mocha/server/sampleServerTest.js is mocha
I20150219-11:58:34.745(-8)? [velocity] File scan complete, now watching /tests
I20150219-11:58:34.745(-8)? [velocity] Triggering queued startup functions
I20150219-11:58:34.761(-8)? [proxy-package-sync] Test file added tests/mocha/client/sampleClientTest.js
I20150219-11:58:34.762(-8)? [proxy-package-sync] Test file added tests/mocha/server/sampleServerTest.js
I20150219-11:58:34.774(-8)? [velocity] Mirror requested { framework: 'mocha',
I20150219-11:58:34.774(-8)?   rootUrlPath: '?mocha=true',
I20150219-11:58:34.774(-8)?   port: 5000,
I20150219-11:58:34.774(-8)?   host: 'http://localhost:5000/',
I20150219-11:58:34.774(-8)?   rootUrl: 'http://localhost:5000/?mocha=true' }
I20150219-11:58:34.775(-8)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20150219-11:58:34.775(-8)? [node-soft-mirror]: LongRunningChildProcess.spawn() { command: '/Users/robertdickert/.meteor/packages/meteor-tool/.1.0.40.1cqymxh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/bin/node',
I20150219-11:58:34.775(-8)?   args: [ '/Users/robertdickert/code/tmp/testvelo/.meteor/local/build/main.js' ],
I20150219-11:58:34.775(-8)?   options:
I20150219-11:58:34.775(-8)?    { detached: true,
I20150219-11:58:34.776(-8)?      cwd: '/Users/robertdickert/code/tmp/testvelo',
I20150219-11:58:34.776(-8)?      env:
I20150219-11:58:34.776(-8)?       { PORT: 5000,
I20150219-11:58:34.776(-8)?         HOST: 'http://localhost:5000/',
I20150219-11:58:34.776(-8)?         ROOT_URL_PATH: '?mocha=true',
I20150219-11:58:34.776(-8)?         ROOT_URL: 'http://localhost:5000/?mocha=true',
I20150219-11:58:34.777(-8)?         FRAMEWORK: 'mocha',
I20150219-11:58:34.777(-8)?         MONGO_URL: 'mongodb://127.0.0.1:3001/mocha',
I20150219-11:58:34.777(-8)?         PARENT_URL: 'http://localhost:3000/',
I20150219-11:58:34.778(-8)?         IS_MIRROR: true,
I20150219-11:58:34.778(-8)?         METEOR_SETTINGS: '{}',
I20150219-11:58:34.778(-8)?         TERM_PROGRAM: 'iTerm.app',
I20150219-11:58:34.778(-8)?         SHELL: '/bin/zsh',
I20150219-11:58:34.778(-8)?         TERM: 'xterm-256color',
I20150219-11:58:34.778(-8)?         TMPDIR: '/var/folders/w7/6vrd75n50fx2g7hg2sx21_vw0000gn/T/',
I20150219-11:58:34.778(-8)?         Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.XLvCiDNTiC/Render',
I20150219-11:58:34.778(-8)?         OLDPWD: '/Users/robertdickert/.meteor/packages/meteor-tool/1.0.40/meteor-tool-os.osx.x86_64',
I20150219-11:58:34.778(-8)?         ANSIBLE_HOSTS: '/Users/robertdickert/ansible_hosts',
I20150219-11:58:34.778(-8)?         USER: 'robertdickert',
I20150219-11:58:34.779(-8)?         SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.MFIVwEvxWn/Listeners',
I20150219-11:58:34.779(-8)?         __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
I20150219-11:58:34.779(-8)?         PAGER: 'less',
I20150219-11:58:34.779(-8)?         LSCOLORS: 'Gxfxcxdxbxegedabagacad',
I20150219-11:58:34.779(-8)?         PATH: '/usr/local/bin:/Users/robert/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11R6/bin:/usr/local/share/npm/bin',
I20150219-11:58:34.779(-8)?         VELOCITY_DEBUG_MIRROR: '1',
I20150219-11:58:34.779(-8)?         PWD: '/Users/robertdickert/code/tmp/testvelo',
I20150219-11:58:34.779(-8)?         LANG: 'en_US.UTF-8',
I20150219-11:58:34.780(-8)?         ITERM_PROFILE: 'Default',
I20150219-11:58:34.870(-8)?         XPC_FLAGS: '0x0',
I20150219-11:58:34.871(-8)?         XPC_SERVICE_NAME: '0',
I20150219-11:58:34.871(-8)?         HOME: '/Users/robertdickert',
I20150219-11:58:34.871(-8)?         COLORFGBG: '12;8',
I20150219-11:58:34.871(-8)?         SHLVL: '1',
I20150219-11:58:34.871(-8)?         VELOCITY_DEBUG: '1',
I20150219-11:58:34.872(-8)?         ITERM_SESSION_ID: 'w0t1p0',
I20150219-11:58:34.872(-8)?         GNUTERM: 'X11',
I20150219-11:58:34.872(-8)?         LOGNAME: 'robertdickert',
I20150219-11:58:34.872(-8)?         LESS: '-R',
I20150219-11:58:34.872(-8)?         LC_CTYPE: 'en_US.UTF-8',
I20150219-11:58:34.872(-8)?         MOCHA_WEB_DEBUG: '1',
I20150219-11:58:34.872(-8)?         SECURITYSESSIONID: '186a7',
I20150219-11:58:34.872(-8)?         DEBUG: '1',
I20150219-11:58:34.872(-8)?         MOBILE_DDP_URL: 'http://localhost:3000',
I20150219-11:58:34.872(-8)?         MOBILE_ROOT_URL: 'http://localhost:3000',
I20150219-11:58:34.872(-8)?         MONGO_OPLOG_URL: 'mongodb://127.0.0.1:3001/local',
I20150219-11:58:34.872(-8)?         APP_ID: '1e8zipm10pxfip1d4v8i2',
I20150219-11:58:34.872(-8)?         NODE_ENV: 'development',
I20150219-11:58:34.872(-8)?         HTTP_FORWARDED_COUNT: '1',
I20150219-11:58:34.873(-8)?         ENABLE_METEOR_SHELL: 'true',
I20150219-11:58:34.873(-8)?         METEOR_PARENT_PID: '1210',
I20150219-11:58:34.873(-8)?         METEOR_PRINT_ON_LISTEN: 'true' } } }
I20150219-11:58:34.873(-8)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20150219-11:58:34.873(-8)? [node-soft-mirror]: /Users/robertdickert/code/tmp/testvelo/.meteor/local/build/programs/server/assets/packages/velocity_node-soft-mirror/lib/spawnScript.js
I20150219-11:58:34.873(-8)? [node-soft-mirror]: The pid of the main Meteor app process is 1210
I20150219-11:58:34.873(-8)? [node-soft-mirror]: LongRunningChildProcess.spawn is spawning 'node'
I20150219-11:58:34.873(-8)? [node-soft-mirror]: LongRunningChildProcess._setPid(pid=1231)
I20150219-11:58:34.873(-8)? [node-soft-mirror]: Saving mocha pid 1231 to /Users/robertdickert/code/tmp/testvelo/.meteor/local/run/mocha.pid
I20150219-11:58:34.874(-8)? [velocity-node-mirror] Mirror process forked with pid 1231
I20150219-11:58:34.969(-8)? [proxy-package-sync] Checking if a new package.js needs to be written because {} undefined
I20150219-11:58:34.969(-8)? [proxy-package-sync] Generating in-memory package.js
I20150219-11:58:34.969(-8)? [proxy-package-sync] Fixture files list length:  0
I20150219-11:58:34.970(-8)? [proxy-package-sync] Test files list length:  2
I20150219-11:58:34.970(-8)? [proxy-package-sync] Test file will be included in mirror tests/mocha/client/sampleClientTest.js
I20150219-11:58:34.970(-8)? [proxy-package-sync] Test file will be included in mirror tests/mocha/server/sampleServerTest.js
I20150219-11:58:34.971(-8)? [proxy-package-sync] Comparing:
I20150219-11:58:34.971(-8)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150219-11:58:34.971(-8)? [proxy-package-sync] - - - - - - - - - currentPackageJS: - - - - - - - - - - - - -
I20150219-11:58:34.971(-8)? Package.describe({
I20150219-11:58:34.971(-8)? 	name: "velocity:test-proxy",
I20150219-11:58:34.971(-8)? 	summary: "Dynamically created package to expose test files to mirrors",
I20150219-11:58:34.971(-8)? 	version: "0.0.4",
I20150219-11:58:34.972(-8)? 	debugOnly: true
I20150219-11:58:34.972(-8)? });
I20150219-11:58:34.972(-8)?
I20150219-11:58:34.972(-8)? Package.onUse(function (api) {
I20150219-11:58:34.972(-8)? 	api.use("coffeescript", ["client", "server"]);
I20150219-11:58:34.972(-8)? 	api.add_files("tests/mocha/client/sampleClientTest.js",["client"]);
I20150219-11:58:34.972(-8)? 	api.add_files("tests/mocha/server/sampleServerTest.js",["server"]);
I20150219-11:58:34.972(-8)? });
I20150219-11:58:34.973(-8)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150219-11:58:34.973(-8)? [proxy-package-sync] - - - - - - - - - generatedPackageJsContent - - - - - - - - -
I20150219-11:58:34.974(-8)? Package.describe({
I20150219-11:58:34.974(-8)? 	name: "velocity:test-proxy",
I20150219-11:58:34.974(-8)? 	summary: "Dynamically created package to expose test files to mirrors",
I20150219-11:58:34.974(-8)? 	version: "0.0.4",
I20150219-11:58:34.974(-8)? 	debugOnly: true
I20150219-11:58:34.974(-8)? });
I20150219-11:58:34.974(-8)?
I20150219-11:58:34.974(-8)? Package.onUse(function (api) {
I20150219-11:58:34.974(-8)? 	api.use("coffeescript", ["client", "server"]);
I20150219-11:58:34.974(-8)? 	api.add_files("tests/mocha/client/sampleClientTest.js",["client"]);
I20150219-11:58:34.974(-8)? 	api.add_files("tests/mocha/server/sampleServerTest.js",["server"]);
I20150219-11:58:34.974(-8)? });
I20150219-11:58:34.974(-8)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150219-11:58:34.974(-8)? [proxy-package-sync] No changes to package.js file required

**Comment by rissem** [comment]
Could you submit your project as a test repo? Tests are working for me w/ the old soft-mirror (I do have node installed), and after installing the latest soft-mirror (0.3.1)

**Comment by rdickert** [comment]
Sure. It's just the default app, but maybe I set something up differently...

https://github.com/rdickert/mocha-issue-132

**Comment by rissem** [comment]
Thanks, it didn't work for me either. I just released mike:mocha@0.5.2, which depends on the latest soft-mirror and it's working now. Please reopen if you're still having issues.
