### ISSUE TITLE
Content from coffee source files not accessible in tests

### ISSUE THREAD

**Issue by Tolmark12** [mad-eye/meteor-mocha-web#134]
I'm trying to test my app written in coffeescript, but app variables aren't accessible in my tests. 

```coffeescript
# People.coffee
People = new Mongo.Collection("people")
```

```coffeescript
# tests/mocha/client/TestPeople.coffee
People.findOne() # Fails because variable 'People' not available at this scope
```

I know meteor gets around this by adding a [share object](http://docs.meteor.com/#/full/coffeescript) sharable across coffeescript files found in the same package. 

```Coffeescript
share.People = new Mongo.Collection("people")
```

I could place everything in the global namespace..
```coffeescript
# People.coffee
@People = new Mongo.Collection("people")
```

..but want to avoid that if at all possible. Is  there is an existing pattern / solution I'm missing, or a cleaner way reference app variables in tests?

**Comment by rissem** [comment]
No great answer here..I generally have one global variable called something like 'App' that I put all my collections under.

If anyone else has ideas here, please chime in.

**Comment by Tolmark12** [comment]
thanks @rissem, this is what I've ended up doing.
