### ISSUE TITLE
Login on a test on server side - How to test a logged user?  

### ISSUE THREAD

**Issue by aj07mm** [mad-eye/meteor-mocha-web#135]
Hi, 
how i can test a logged user to access Meteor.user() in the sampleServerTest.js ??

All the methods to log a user is client side.

**Comment by rissem** [comment]
I would probably write these as client side tests, and use methods (maybe test methods that you write) to test the server side components with a logged in user.

Alternatively you could mock Meteor.user() with something like [sinon](https://github.com/practicalmeteor/meteor-sinon)

Finally, I bet there is an undocumented method for logging in a user on the server side. I'd dig around in the meteor-accounts[https://github.com/meteor/meteor/tree/devel/packages/accounts-base) package, and see what you find. Good luck!

**Comment by svanderbleek** [comment]
Yeah "Good luck"

**Comment by svanderbleek** [comment]
It's hacky but redefining this DDP method works

```javascript
DDP._CurrentInvocation.get = function() {
  return {
    userId: 'someUserId'
  };
}
```

**Comment by ryanmtaylor** [comment]
quick (maybe obvious) note: for @svanderbleek's solution I had to import (`api.use`) the `ddp` package in my package.js
