### ISSUE TITLE
Static 5000 Port

### ISSUE THREAD

**Issue by thepig25** [mad-eye/meteor-mocha-web#141]
Hey having issues running Mocha, in Velocity. Note Also using Cucumber and webdiver through Velocity. Both use Port 5000

I know for velocity-jasmine.  The following was added. 
```
JASMINE_MIRROR_PORT=5050 meteor
```

Would be great to see something similar in meteor-mocha-web

**Comment by ifell** [comment]
+1

**Comment by alpjor** [comment]
+1

**Comment by aleksanderrojiou** [comment]
+1

**Comment by rissem** [comment]
Fixed with https://github.com/mad-eye/meteor-mocha-web/pull/165

Will push out a release soon.
