### ISSUE TITLE
Mocking HTTP calls with nock-vcr-recorder-mocha

### ISSUE THREAD

**Issue by semikolon** [mad-eye/meteor-mocha-web#144]
I need to mock HTTP calls in my tests.

I found https://github.com/poetic/nock-vcr-recorder-mocha but including it in my app using https://github.com/meteorhacks/npm and with the following test code

    vcr = Meteor.npmRequire('nock-vcr-recorder-mocha')
    log "VCR!",vcr

    describe "Interpret data", ->
        vcr.it "should work", ->
            chai.expect(->
              # http call
            ).not.to.throw()

it gives me the error:

    W20150327-17:25:33.820(1)? (STDERR) mocha: 1 tests failed
    W20150327-17:25:33.820(1)? (STDERR) should work
    W20150327-17:25:33.820(1)? (STDERR) Cannot read property 'test' of undefined
    W20150327-17:25:33.820(1)? (STDERR) TypeError: Cannot read property 'test' of undefined
    W20150327-17:25:33.821(1)? (STDERR)     at getCassetteName (/Users/fredrikbranstrom/Sites/kaus/.meteor/local/isopacks/npm-container/npm/node_modules/nock-vcr-recorder-mocha/lib/it.js:30:24)
    W20150327-17:25:33.821(1)? (STDERR)     at /Users/fredrikbranstrom/Sites/kaus/.meteor/local/isopacks/npm-container/npm/node_modules/n

**Comment by rissem** [comment]
I'm completely unfamiliar with VCR, and not too familiar with meteorhacks/npm either. I'd probably go with something a little more mature like [sinon](https://github.com/practicalmeteor/meteor-sinon) which has already been wrapped to work with Meteor. It will require a little more manual mocking on your end, but it shouldn't be too painful.

If you do manage to get VCR working though, I'd be excited to check it out. I appreciated it a lot when I was in the Ruby world. My guess is it'll be more involved than just using meteorhacks/npm. I'd take a look at https://www.discovermeteor.com/blog/wrapping-npm-packages/ if you're interested in taking that on. Good luck!

**Comment by semikolon** [comment]
Probably gonna use nock directly for now.
ons 1 apr 2015 kl. 19:41 skrev Michael Risse <notifications@github.com>:
