### ISSUE TITLE
running tests against a different URL?

### ISSUE THREAD

**Issue by dcsan** [mad-eye/meteor-mocha-web#146]
I'd like to run some tests against my production site post deployment. Is there a way to change the base URL that mocha-web is running against?

obviously I won't be able to do things like get directly at the DB, or unit tests, but for some basic integration flow tests it would be useful. I could also expose test API endpoints if i do want to check the state of certain data.

**Comment by rissem** [comment]
I haven't tried to do this at all yet. You should be able to point something like WebDriver at whatever site you want (even something that's not Meteor) https://github.com/xolvio/meteor-webdriver Would that work for you or do you require access to the JavaScript scope on the page?

**Comment by dcsan** [comment]
thanks for the tip rissem. i'll try that!

**Comment by rissem** [comment]
Good luck! Closing this for now. Feel free to add more here if you figure out some good techniques for testing against your deployed app.

**Comment by dcsan** [comment]
from my colleague:

> So. I made a bit of investigation about xolvio:webdriver and as far as I understand it's purpose is to be run via "meteor --test". It launches the app in the background and then runs the tests. I don't understand how do I run the tests against remote instance of the app. So I guess we better stick with separate set of testing scripts

so I think we just need to use standard webdriver.io as a node app?

**Comment by rissem** [comment]
Pretty sure it should be usable w/o the `--test` flag. Regardless, it sounds like we could use a better example.
