### ISSUE TITLE
Mocha not working in Meteor 1.1.0.2 for Windows

### ISSUE THREAD

**Issue by rollymaduk** [mad-eye/meteor-mocha-web#152]
Installed a new meteor app and added the `mike:mocha` package, but got **0 tests passed** as the html-reporter result. Added sample tests and changed the contents of sample-test files but nothing works. It just remains the same,browser doesn't refresh and everything just remains the same.

**Comment by yuomtheara** [comment]
I have the same problem.

**Comment by rollymaduk** [comment]
@yuomtheara the issue has been addressed [here](https://github.com/meteor-velocity/velocity/issues/303#)
