### ISSUE TITLE
Confusion mike:mocha-package & mike:mocha

### ISSUE THREAD

**Issue by marcodejongh** [mad-eye/meteor-mocha-web#153]
Right now when you click the github link in atmosphere for mocha-package you end up in this repository causing a lot of confusion. Because of that it is not clear where the documentation is, it feels like ```mocha-package``` has a erroneous ```package.js```.

It took me quite some time to figure that out that mocha-package is on a separate branch.

Maybe it would be a better idea to create a fork of this repository instead of developing two packages on different branches in the same repository.

Or abstracting away shared logic to a separate ```mocha-core``` package.

Or at the very least add a big message in the README.md.

**Comment by rissem** [comment]
Sorry @marcodejongh, I hate wasting people's time like that. And thanks for letting me know this was confusing. I added a big notice to the bottom of the README. Let me know if you think it needs anything else for now. Soon I plan to support just one package, or possibly abstract shared logic into a `mocha-core` package as you suggested.

**Comment by marcodejongh** [comment]
@rissem In the end, I'm just very happy I can finally use mocha for testing my packages!

It just took me some extra time to figure out how run it on jenkins.
