### ISSUE TITLE
Routing wildcard iFrame

### ISSUE THREAD

**Issue by stephan281094** [mad-eye/meteor-mocha-web#155]
Hello there,

When using both Iron Router and meteor-mocha-web, I run into a problem:
When I open the html-reporter, and I take a look at the iframe that includes the mochaWeb template, I get a 404 page not found. With Iron Router, I configured a notfound template that gets rendered when there's no matching route. [`mirror.rootUrl + mirror.rootUrlPath + "&lastModified=" + mirror.lastModified`](https://github.com/mad-eye/meteor-mocha-web/blob/master/client.js#L48) doesn't result in an existing route, so it renders the notfound template.

Not sure if this is an issue that should be directed at mike:mocha or velocity-core, but does anyone have a solution to this problem? Maybe by only using query strings in the url or something?

**Comment by aaronjudd** [comment]
The offending line is in mocha-web, as also mentioned in #156

**Comment by stephan281094** [comment]
Ah, thanks for the reference.
