### ISSUE TITLE
appending &lastModified to the url is not as good as it seems.

### ISSUE THREAD

**Issue by brugnara** [mad-eye/meteor-mocha-web#156]
This line (https://github.com/mad-eye/meteor-mocha-web/blob/ae0338270f1eb985e97451bce1967060605bbfc6/client.js#L48) breaks the home page trying to open

`http://localhost:3000/&lastModified=TIMESTAMP`

**Comment by stephan281094** [comment]
I am having issues with this as well in combination with not found templates. See #155.
Is there a temp (or permanent) fix for this?
Maybe use query parameters or something?

**Comment by aaronjudd** [comment]
well, as a temp patch, if you could:
```coffeescript
Router.map ->
  # custom 404 Page
  @route "notFound",
    path: "/(.*)"
    action: ->
      if @params[0].indexOf("lastModified")
        Router.go('/?mocha=true' + @params )
```
