### ISSUE TITLE
before(), after(), it() methods being called twice

### ISSUE THREAD

**Issue by diegoalberto** [mad-eye/meteor-mocha-web#166]
Hi, there is a problem I'm facing setting up the test database: before and after calls are being called twice, the same for it statements so it messes up my tests configurations.

To reproduce the problem:

meteor create mocha-test
cd mocha-test
meteor add mike:mocha
meteor start

No I added ./tests/mocha/server/sampleServerTest.js with the following data:

if (!(typeof MochaWeb === 'undefined')){
  MochaWeb.testOnly(function(){

    describe("Server initialization", function(){

      console.log('Server initialization describe called');

      before(function() {
        console.log('before called');
      });

      after(function() {
        console.log('after called');
      })

      it("should have a Meteor version defined", function(){

        console.log('should have a Meteor version defined it called');

        chai.assert(Meteor.release);

      });

    });
  });
}

After the tests get run I'm having this on the ./.meteor/local/log/mocha.log file:

...
[34mI20150507-18:19:52.699(-5)? [39m[velocity] Starting mirror on port 59332
[34mI20150507-18:19:52.744(-5)? [39mSETUP GLOBALS
[34mI20150507-18:19:52.746(-5)? [39mServer initialization describe called
[34mI20150507-18:19:52.750(-5)? [39mMOCHA-WEB MIRROR LISTENING AT http://localhost:59332/
[34mI20150507-18:19:52.750(-5)? [39mPARENT URL http://localhost:3000/
=> Meteor server restarted
[34mI20150507-18:19:52.777(-5)? [39mRunning mocha server tests
[34mI20150507-18:19:52.809(-5)? [39m[velocity] Established connection with Velocity.
[34mI20150507-18:19:52.816(-5)? [39mRunning mocha server tests
[34mI20150507-18:19:52.817(-5)? [39mbefore called
[34mI20150507-18:19:52.823(-5)? [39mshould have a Meteor version defined it called
[34mI20150507-18:19:52.829(-5)? [39mafter called
[34mI20150507-18:19:52.851(-5)? [39mbefore called
[34mI20150507-18:19:52.852(-5)? [39mshould have a Meteor version defined it called
[34mI20150507-18:19:52.853(-5)? [39mafter called

This is a problem if you setup collection entries at before call, or move files around for testing.

Thanks.

**Comment by diegoalberto** [comment]
We have also found that the second time the test runs generates a timeout on it tests that includes asynchronous calls

**Comment by diegoalberto** [comment]
This is happening after meteor reloads, the first time the tests run there are no duplicates.

**Comment by rissem** [comment]
Going to look into this first thing tomorrow

**Comment by diegoalberto** [comment]
Thanks, looking forward for it!

**Comment by rissem** [comment]
Could you please try with the mocha rc I just pushed and see if that fixes things?

`meteor add mike:mocha@0.6.0-rc-1`

**Comment by diegoalberto** [comment]
You're the best! The thing works as expected now. Many tests I thought where broken or not properly started working again =D, this is a major bugfix!

**Comment by rissem** [comment]
Awesome, couldn't have hoped for a better response :smile:
