### ISSUE TITLE
Intermittent error: Callback tests are getting "timeout of 5000ms exceeded"

### ISSUE THREAD

**Issue by rbrugnollo** [mad-eye/meteor-mocha-web#167]
Hi, I'm having problems trying to run this test:

    if (!(typeof MochaWeb === 'undefined')) {
        MochaWeb.testOnly(function () {

            describe("Simple timeout test", function () {
                describe('test timeout and async calls', function(){
                    var count = 0;
                    this.timeout(5000);

                    it('should take less than 500ms', function(done){
                        console.log('running should take less than 500ms: ' + (++count));
                        var callbackFunc = function(){
                            chai.assert.equal(5, 5);
                            setTimeout(done, 800);
                        };
                        callbackFunc();
                    })
                });
                });
        });
    }

and I'm getting this error:

I20150508-21:22:52.899(-3)? [sanjo:long-running-child-process]: Exposing imports for testing purposes
I20150508-21:22:52.906(-3)? [velocity] Starting mirror on port 53732
I20150508-21:22:52.968(-3)? SETUP GLOBALS
I20150508-21:22:53.243(-3)? MOCHA-WEB MIRROR LISTENING AT http://localhost:53732/
I20150508-21:22:53.244(-3)? PARENT URL http://localhost:3000/
I20150508-21:22:53.282(-3)? Running mocha server tests
=> Meteor server restarted
I20150508-21:22:53.328(-3)? running should take less than 500ms: 1
I20150508-21:22:53.355(-3)? [velocity] Established connection with Velocity.
I20150508-21:22:53.411(-3)? Running mocha server tests
I20150508-21:22:53.435(-3)? running should take less than 500ms: 2
I20150508-21:22:58.328(-3)? timeout of 5000ms exceeded
I20150508-21:22:58.330(-3)? Error: timeout of 5000ms exceeded
I20150508-21:22:58.331(-3)?     at [object Object]._onTimeout (/home/rbrugnollo/.meteor/packages/mike_mocha/.0.5.4.1ijkyvk++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runnable.js:175:14)
I20150508-21:22:58.331(-3)?     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
I20150508-21:22:58.331(-3)? timeout of 5000ms exceeded
I20150508-21:22:58.333(-3)? Error: timeout of 5000ms exceeded
I20150508-21:22:58.333(-3)?     at [object Object]._onTimeout (/home/rbrugnollo/.meteor/packages/mike_mocha/.0.5.4.1ijkyvk++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runnable.js:175:14)
I20150508-21:22:58.333(-3)?     at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

This is not happening always, but I'd say I'm getting the errors 8 in 10 times I run the test.

As you can see, there's also another problem... The test's been running twice.

tks!

**Comment by diegoalberto** [comment]
https://github.com/mad-eye/meteor-mocha-web/issues/166 related

**Comment by rissem** [comment]
Could you please try with the mocha rc I just released and see if that fixes things?

`meteor add mike:mocha@0.6.0-rc-1`

**Comment by diegoalberto** [comment]
Fixes for me, many thanks!

**Comment by rbrugnollo** [comment]
@rissem the problem has been solved. Thank you very much!

I'm gonna close the issue.
