### ISSUE TITLE
meteor run --test hangs indefinitely when run on CodeShip

### ISSUE THREAD

**Issue by mhwheeler** [mad-eye/meteor-mocha-web#168]
`meteor run --test` hangs indefinitely when run on CodeShip using `velocity-examples/leaderboard-mocha`. I'm using leaderboard-mocha as a "minimal" reproduction case, since I'm having trouble with a private project.

## Steps to reproduce:

(If you use my fork and codeship project which i've given access to you can skip these steps and just click "restart build")

1. Make a fork of [meteor-velocity/velocity-examples](https://github.com/meteor-velocity/velocity-examples)
  - ex. [mhwheeler/velocity-examples](https://github.com/mhwheeler/velocity-examples)
2. Create a CodeShip project
  - Go to [https://codeship.com/](https://codeship.com/)
  - sign in / sign up (link with github account)
  - click "Select Project > Create New Project" (free for open source)
  - click "Connect with the github repository"
  - select your new fork of `velocity-examples` created in step 1
  - Enter these basic "Setup Commands":

    ```shell
    nvm install 0.10.35
    nvm use 0.10.35
    curl -o meteor_install_script.sh https://install.meteor.com/
    chmod +x meteor_install_script.sh
    sed -i "s/type sudo >\/dev\/null 2>&1/\ false /g" meteor_install_script.sh
    ./meteor_install_script.sh
    export PATH=$PATH:~/.meteor/
    meteor --version
    cd leaderboard-mocha
    ```
  - Enter these "Test Commands":

    ```shell
    meteor run --test
    ```

3. Trigger a CodeShip build by changing a file in the fork.
4. Watch CodeShip build log
	`meteor run --test`
	
	```
	stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
	I20150516-00:26:17.374(0)? [velocity] mocha is starting a mirror at http://localhost:39680/.
	I20150516-00:26:17.376(0)? [velocity] This takes a few minutes the first time.
	I20150516-00:26:17.376(0)? [velocity] You can see the mirror logs at: tail -f /home/rof/src/github.com/mhwheeler/velocity-examples/leaderboard-mocha/.meteor/local/log/mocha.log
	PASSED mocha : Server initialization => should insert players into the database after server start
	```
	- Note that only one test reports passed.
	- There's no summary and the process does not end.
	- It is killed automatically by CodeShip after a while for inactivity.

	
Other comments:

- I tried forcing different Mocha versions by adding `meteor add mike:mocha@0.5.2` or `meteor add mike:mocha@0.6.0-rc-1` to the bottom of the Setup Commands. Same result.
- This could easily be something specific to the CodeShip environment but I need help investigating what that could be.
- I added rissem@gmail.com to [https://codeship.com/projects/80291/](https://codeship.com/projects/80291/)
- I added @rissem to my fork.
- On the build screen you can spin up a CodeShip environment. Click "Open SSH Debug Session". Note that you then have to run the setup and test steps yourself.

**Comment by tmikoss** [comment]
Have you tried `meteor --test --release velocity:METEOR@1.1.0.2_2` as per readme? It fixed a similar problem for me.

**Comment by rissem** [comment]
Thanks for pointing that out @tmikoss 

You might also want to try out the new release candidate for mocha `mike:mocha@0.6.0-rc-1`. It fixes quite a few issues around tests running twice, not finishing, etc.

**Comment by mhwheeler** [comment]
I had already tried `mike:mocha@0.6.0-rc-1` to no avail. @tmikoss 's suggestion of `--release velocity:METEOR@1.1.0.2_2` works! I have been using mocha for months so hadn't seen the update in the readme :cold_sweat:. Thanks so much for the quick responses both of you!
