### ISSUE TITLE
mocha-packages hangs on travis-ci

### ISSUE THREAD

**Issue by crenwick** [mad-eye/meteor-mocha-web#169]
With `mike:mocha-package` installed, 
```sh
$ meteor test-packages --velocity --driver-package velocity:console-reporter ./
```
runs perfectly on my local dev machines, but hangs on travis.

It just spits out
```sh
[[[[[ Tests ]]]]]
=> Started proxy.
=> Started MongoDB.
grove:grove-api: updating npm dependencies -- spark...
=> Babel active on file extensions: es6.js, es6, jsx
I20150520-19:28:42.257(0)? Not logging into Spark
I20150520-19:28:42.384(0)? [velocity] chokadir watching /tmp/meteor-test-run1pl7ecc/tests
I20150520-19:28:42.446(0)? [velocity] chokadir watching /tmp/meteor-test-run1pl7ecc/tests
=> Started your app.
=> App running at: http://localhost:3000/
```
and Travis kills it after 10 minutes.

**Comment by chmac** [comment]
Do you maybe have phantomjs installed on your dev machines but not in travis?

**Comment by chmac** [comment]
Or maybe you're missing the `fontconfig` package which phantomjs requires in order to run [apparently](https://github.com/ariya/phantomjs/issues/10904).

I can't get it to run locally never mind on CI, so I'm just guessing! :-)

**Comment by crenwick** [comment]
Running Phantomjs 1.9.8 on both machines. Just tried the fontconfig fix, but it appeared to already have that package as well...

**Comment by crenwick** [comment]
Looks like if the package is cloned into a /packages/ directory of a functioning meteor app, that command works fine. However, if the package is cloned into an independent repo it hangs and never launches phantomjs. The console reporting still works if I open the browser, but the command doesn't close either.

Looks like more of an issue with the console-reporter than mocha. Still not sure how anyone is getting this to work on travis-ci...

**Comment by chmac** [comment]
I had a similar issue locally. I could run the tests, but only if I opened a browser. No idea why, but the following works for me both locally and on CircleCI:

    VELOCITY_DEBUG_MIRROR=1 VELOCITY_CI=1 meteor test-packages --velocity --driver-package respondly:test-reporter

I experimented with various other environment variables, and narrowed it down to these 2. If they're both present, my tests run, and then meteor exits. Otherwise, meteor never exits.

**Comment by crenwick** [comment]
Interesting. That command doesn't behave any different for me. It will still will only trigger a test runner if the repo is cloned into the /packages/ of a meteor app.

**Comment by chmac** [comment]
Oh, apologies, I didn't notice that you're testing just a single package without the whole app. I wasn't trying that, I'm testing the packages in the context of an app.

**Comment by crenwick** [comment]
Just opened an issue here: https://github.com/meteor-velocity/velocity/issues/333.

**Comment by crenwick** [comment]
Solved here: https://github.com/meteor-velocity/velocity/issues/333#issuecomment-104402730

Issue was that if you don't bring in mike:mocha-package with an explicit version number (i.e. `'mike:mocha-package@0.5.8'`), then meteor defaults to an older, broken version.

**Comment by chmac** [comment]
Sadly, I am also [familiar](https://github.com/meteor/meteor/issues/4170) with that issue! Meteor chooses old versions unless an explicit version constraint is specified. Glad you were able to resolve it anyway.
