### ISSUE TITLE
Debug the test?

### ISSUE THREAD

**Issue by sf-wind** [mad-eye/meteor-mocha-web#171]
Velocity 0.6.0 has the capability to debug the server side of the tests. But as I follow the instructions in the release note, I still cannot debug it. What is the problem? 

Debugging Mirrors

You can now debug the server side of mirrors. This allows you to debug your server integration tests.

export VELOCITY_DEBUG_MIRROR=jasmine-server-integration
meteor
After the mirror has started you can connect to the web debugger by browsing to http://localhost:8080/debug?port=5858. This works exactly the same way as meteor debug for your main app. You can find more info in the official Meteor documentation.

**Comment by nicoles** [comment]
Same, is there any way to get to a debugger with mocha, or do I need to switch over to jasmine?

**Comment by rissem** [comment]
Sorry for the late responses. This is possible with

`VELOCITY_DEBUG_MIRROR=mocha meteor`

I'll update the README right after this.
