### ISSUE TITLE
Top Banner is overlaying the Velocity Section

### ISSUE THREAD

**Issue by rwatts3** [mad-eye/meteor-mocha-web#176]
I am testing packages with mocha-package , and the respondly section is overlaying the velocity section. Is this the same experience for everyone else ? 

http://screencast.com/t/Lz8OLYLGepLe

**Comment by rissem** [comment]
@rwatts3 sorry for not getting back to you sooner. It looks like something is including the velocity:html-reporter. This shouldn't be used w/ mocha package testing.
