### ISSUE TITLE
Update mocha package example for CI

### ISSUE THREAD

**Issue by zimme** [mad-eye/meteor-mocha-web#177]
How about updating the README for mocha-package to use `velocity:console-reporter` in the CI/Headless example?

**Comment by alpjor** [comment]
+1

**Comment by chmac** [comment]
Doesn't make any difference for me, in both cases, meteor intermittently fails to exit. Is there an advantage to using the console reporter? I also see logs in the console whether I run it with either `velocity:console-reporter` or `respondly:test-reporter`.

**Comment by zimme** [comment]
I haven't had any problems with meteor exiting my tests for [`zimme:active-route`](https://github.com/zimme/meteor-active-route).

And I guess not, maybe the styling of the output is a bit different?

I'll have to close this if what you say is true, then the docs don't need updating as `respondly:test-reporter`also reports to the cli

**Comment by zimme** [comment]
So I just checked and `respondly:test-reporter` actually reports to the cli too, the only difference is that `velocity:console-reporter` prints an extra line with how many test that passed at the end.

So I guess I'll close this issue as you can use `respondly:test-reporter` without a problem.

Thanks @chmac for pointing that out.
