### ISSUE TITLE
Is the packageTests branch maintained?

### ISSUE THREAD

**Issue by chmac** [mad-eye/meteor-mocha-web#180]
First off, thanks for the work on the packageTests branhc, it's awesome.

I'm seeing a few issues reported around a month ago, some longer, and no responses on any of them.

@mad-eye Is the package still maintained? Interested in pointing people at a fork if somebody else takes over maintenance?

I'm thinking specifically of #161. We built a load of tests and now we're trying to get CI working and not having any luck.

**Comment by rissem** [comment]
I'm still maintaining it, but I'm devoting limited time to it as you can probably tell. Replied regarding #161 separately. Thanks for bringing this issue back up. I definitely want this to work reliably in a CI setting.
