### ISSUE TITLE
[packageTest] Failed tests report success in CI

### ISSUE THREAD

**Issue by chmac** [mad-eye/meteor-mocha-web#181]
I'm seeing tests where an assertion exception was thrown, but the final result is still:

    TESTS RAN SUCCESSFULLY

I initially tried reporting this here Respondly/meteor-test-reporter#37 but they pointed me back to this repo.

**Comment by rissem** [comment]
It probably is an issue with mocha. Do you see the same error when running in non-CI mode?

I've also seen issues where a test's done callback is called before the assertion error is thrown, and the test is marked as a success.

A reproduction repo would be super helpful if you have the time.

**Comment by rissem** [comment]
@chmac any updates on this?

**Comment by chmac** [comment]
Haven't seen it again. It might have been related to our problem of loading this package only on the server and not on the client. Happy to close the issue and reopen again if we see this again. Thanks for the follow up.
