### ISSUE TITLE
Is it possible to specify mocha console reporters

### ISSUE THREAD

**Issue by dmitrijs-balcers** [mad-eye/meteor-mocha-web#183]
I would like to use any of these console reporters: http://mochajs.org/#reporters

Was wondering, if it is possible to change default console reporting look.

**Comment by rissem** [comment]
That would be cool! Unfortunately the integration with Meteor/Velocity relies pretty heavily on a custom reporter that sends back the test results. It might be possible to invoke one of the mocha console reporters after calling the custom reporter. I'm probably not going to get to this any time soon, but I'd be open to a pull request if someone wants to take a stab at it.
