### ISSUE TITLE
Error while testing packages

### ISSUE THREAD

**Issue by sungwoncho** [mad-eye/meteor-mocha-web#184]
When testing packages by running:

    meteor test-packages --velocity --driver-package velocity:console-reporter

No matter the tests pass or fail, I always get:

    error calling testsComplete function { [Error: Match error: Expected string, got undefined]

Please see this repo for reproduction: https://github.com/sungwoncho/meteor-mocha-issue

**Comment by rissem** [comment]
@sungwoncho thanks for reporting, and thanks for a clear reproduction repo.

You shouldn't need to use the console reporter when testing in this way. I was able to successfully run your test at the command line with just

`meteor test-packages --velocity`

And within the browser using

`meteor test-packages --velocity --driver-package respondly:test-reporter`

Hope this helps.
