### ISSUE TITLE
Cannot use with Meteor 1.2 rc-7

### ISSUE THREAD

**Issue by sungwoncho** [mad-eye/meteor-mocha-web#190]
Adding `mike:mocha` causes app to not run correctly if using Meteor 1.2 rc-7. A random test runner occupies the top of the screen.

To reproduce:

(1) Make a new project and run `meteor update --release METEOR@1.2-rc.7` to use 1.2-rc7.
(2) Add mike:mocha (latest version).
(3) When you run the app you will see the following:

![mikemocha](https://cloud.githubusercontent.com/assets/8265228/9566419/5b7fc310-4f48-11e5-8104-e8356d1adf0e.png)

Possible compatibility issue with Meteor 1.2?

**Comment by pavetok** [comment]
+1

**Comment by discdiver** [comment]
+1 (1.2-rc.11)

**Comment by rissem** [comment]
Pointing to the latest velocity/html-reporter seems to have fixed this. Let me know if you're still having issues.

**Comment by sungwoncho** [comment]
Confirming that it is fixed with 0.6.4. Thanks.
