### ISSUE TITLE
ReferenceError: assert is not defined?

### ISSUE THREAD

**Issue by awatson1978** [mad-eye/meteor-mocha-web#20]
Hi there!
Hey, I'm being a ditz, and can't seem to get this to work.  I've installed mocha-web via mrt, set the environment variable, added {{> mochaTestReport }}, and gotten the HTML test runner (yay!).  But then it spits out `ReferenceError: assert is not defined`.  

Is this a Chai thing?  I've tried various things like installing `npm install chai` and adding the line `var assert = require("assert")` to my test file.  But nothing seems to be quite working.

Any ideas????
Thanks!

**Comment by stefek99** [comment]
Weird, shouldn't make any diffence:

> I had to install chai via the package.json file, and running 'npm install', rather than 'npm install chai'

You can use the following syntax: 

`var assert = require('chai').assert;`

Instead of:

`chai.assert.equal(-1, [1,2,3].indexOf(0));`

**Comment by Tyrben** [comment]
Why is assert in *chai* and not in *mocha*? `assert()` is a very generic feature of test frameworks...
