### ISSUE TITLE
Use requestFramework

### ISSUE THREAD

**Issue by samhatoum** [mad-eye/meteor-mocha-web#88]
See this: https://github.com/meteor-velocity/velocity/pull/129

mocha-web should now request a mirror and wait for the returned requestId to be returned. [See here for more details](https://github.com/meteor-velocity/velocity/blob/feature/request_mirror/core.js#L351)

something like:
```javascript
Meteor.call('requestMirror', {framework: 'mocha-web', port: 5000}, function(error,requestId) {
    VelocityMirrors.find({requestId: requestId}).observe({
        added: runTests, changed: runTests
    });
});

or your preferred reactive method

**Comment by rissem** [comment]
Mocha is now using `/velocity/mirrors/request`, see https://github.com/mad-eye/meteor-mocha-web/blob/master/server.js#L63
